// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFCore.App.Data;

#nullable disable

namespace WPFCore.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629033021_AddNewMenus")]
    partial class AddNewMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("WPFCore.App.Modules.Customers.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WPFCore.App.Modules.Menus.Models.MenuItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Glyph")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("menu_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionKey = "Dashboard",
                            IsEnabled = true,
                            SortOrder = 1,
                            Title = "Thống kê"
                        },
                        new
                        {
                            Id = 10,
                            IsEnabled = true,
                            SortOrder = 2,
                            Title = "Danh mục"
                        },
                        new
                        {
                            Id = 11,
                            ActionKey = "MapLayer",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 1,
                            Title = "Quản lý lớp dữ liệu bản đồ"
                        },
                        new
                        {
                            Id = 12,
                            ActionKey = "GeoFeature",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 2,
                            Title = "Quản lý đối tượng địa lý"
                        },
                        new
                        {
                            Id = 13,
                            ActionKey = "DataSource",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 3,
                            Title = "Quản lý nguồn dữ liệu"
                        },
                        new
                        {
                            Id = 14,
                            ActionKey = "CheckRules",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 4,
                            Title = "Quản lý quy định kiểm tra"
                        },
                        new
                        {
                            Id = 15,
                            ActionKey = "MapType",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 5,
                            Title = "Quản lý loại bản đồ"
                        },
                        new
                        {
                            Id = 16,
                            ActionKey = "Users",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 6,
                            Title = "Quản lý người dùng"
                        },
                        new
                        {
                            Id = 20,
                            IsEnabled = true,
                            SortOrder = 3,
                            Title = "Hệ thống"
                        },
                        new
                        {
                            Id = 21,
                            ActionKey = "RunCheck",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 1,
                            Title = "Kiểm tra dữ liệu bản đồ"
                        },
                        new
                        {
                            Id = 22,
                            ActionKey = "CheckResults",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 2,
                            Title = "Xem kết quả kiểm tra"
                        },
                        new
                        {
                            Id = 23,
                            ActionKey = "SummaryReport",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 3,
                            Title = "Báo cáo tổng hợp"
                        },
                        new
                        {
                            Id = 24,
                            ActionKey = "ExportReport",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 4,
                            Title = "Xuất báo cáo (Excel/PDF)"
                        },
                        new
                        {
                            Id = 25,
                            ActionKey = "CustomerList",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 5,
                            Title = "Quản lý khách hàng (CRUD mẫu)"
                        },
                        new
                        {
                            Id = 26,
                            ActionKey = "Menus",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 6,
                            Title = "Quản lý menu"
                        },
                        new
                        {
                            Id = 30,
                            IsEnabled = true,
                            SortOrder = 4,
                            Title = "Trợ giúp"
                        },
                        new
                        {
                            Id = 31,
                            ActionKey = "About",
                            IsEnabled = true,
                            ParentId = 30,
                            SortOrder = 1,
                            Title = "Giới thiệu"
                        },
                        new
                        {
                            Id = 32,
                            ActionKey = "Exit",
                            IsEnabled = true,
                            ParentId = 30,
                            SortOrder = 2,
                            Title = "Thoát"
                        },
                        new
                        {
                            Id = 33,
                            IsEnabled = true,
                            SortOrder = 2,
                            Title = "Bản đồ địa giới"
                        },
                        new
                        {
                            Id = 34,
                            ActionKey = "ViewMap",
                            IsEnabled = true,
                            ParentId = 33,
                            SortOrder = 1,
                            Title = "Xem bản đồ trực quan"
                        });
                });

            modelBuilder.Entity("WPFCore.App.Modules.Menus.Models.MenuItemEntity", b =>
                {
                    b.HasOne("WPFCore.App.Modules.Menus.Models.MenuItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
