// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFCore.App.Data;

#nullable disable

namespace WPFCore.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("WPFCore.App.Modules.Customers.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("WPFCore.App.Modules.Menus.Models.MenuItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionKey")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Glyph")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("menu_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionKey = "Dashboard",
                            IsEnabled = true,
                            SortOrder = 1,
                            Title = "Th?ng kê"
                        },
                        new
                        {
                            Id = 10,
                            IsEnabled = true,
                            SortOrder = 2,
                            Title = "Danh m?c"
                        },
                        new
                        {
                            Id = 11,
                            ActionKey = "MapLayer",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 1,
                            Title = "Qu?n lý l?p d? li?u b?n d?"
                        },
                        new
                        {
                            Id = 12,
                            ActionKey = "GeoFeature",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 2,
                            Title = "Qu?n lý d?i tu?ng d?a lý"
                        },
                        new
                        {
                            Id = 13,
                            ActionKey = "DataSource",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 3,
                            Title = "Qu?n lý ngu?n d? li?u"
                        },
                        new
                        {
                            Id = 14,
                            ActionKey = "CheckRules",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 4,
                            Title = "Qu?n lý quy d?nh ki?m tra"
                        },
                        new
                        {
                            Id = 15,
                            ActionKey = "MapType",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 5,
                            Title = "Qu?n lý lo?i b?n d?"
                        },
                        new
                        {
                            Id = 16,
                            ActionKey = "Users",
                            IsEnabled = true,
                            ParentId = 10,
                            SortOrder = 6,
                            Title = "Qu?n lý ngu?i dùng"
                        },
                        new
                        {
                            Id = 20,
                            IsEnabled = true,
                            SortOrder = 3,
                            Title = "H? th?ng"
                        },
                        new
                        {
                            Id = 21,
                            ActionKey = "RunCheck",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 1,
                            Title = "Ki?m tra d? li?u b?n d?"
                        },
                        new
                        {
                            Id = 22,
                            ActionKey = "CheckResults",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 2,
                            Title = "Xem k?t qu? ki?m tra"
                        },
                        new
                        {
                            Id = 23,
                            ActionKey = "SummaryReport",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 3,
                            Title = "Báo cáo t?ng h?p"
                        },
                        new
                        {
                            Id = 24,
                            ActionKey = "ExportReport",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 4,
                            Title = "Xu?t báo cáo (Excel/PDF)"
                        },
                        new
                        {
                            Id = 25,
                            ActionKey = "CustomerList",
                            IsEnabled = true,
                            ParentId = 20,
                            SortOrder = 5,
                            Title = "Qu?n lý khách hàng (CRUD m?u)"
                        },
                        new
                        {
                            Id = 30,
                            IsEnabled = true,
                            SortOrder = 4,
                            Title = "Tr? giúp"
                        },
                        new
                        {
                            Id = 31,
                            ActionKey = "About",
                            IsEnabled = true,
                            ParentId = 30,
                            SortOrder = 1,
                            Title = "Gi?i thi?u"
                        },
                        new
                        {
                            Id = 32,
                            ActionKey = "Exit",
                            IsEnabled = true,
                            ParentId = 30,
                            SortOrder = 2,
                            Title = "Thoát"
                        });
                });

            modelBuilder.Entity("WPFCore.App.Modules.Menus.Models.MenuItemEntity", b =>
                {
                    b.HasOne("WPFCore.App.Modules.Menus.Models.MenuItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
